EXERCISES = [
    # Weight Training - Chest
    {"name": "Bench Press", "category": "Weight Training", "muscle_group": "Chest", "equipment": "Barbell",
     "difficulty": "Intermediate", "instructions": "Lie on a flat bench, grip the bar slightly wider than shoulder-width, lower to chest, press back up."},
    {"name": "Incline Dumbbell Press", "category": "Weight Training", "muscle_group": "Chest", "equipment": "Dumbbells",
     "difficulty": "Intermediate", "instructions": "On an incline bench, press dumbbells up from shoulder height until arms are extended."},
    {"name": "Push-Up", "category": "Weight Training", "muscle_group": "Chest", "equipment": "Bodyweight",
     "difficulty": "Beginner", "instructions": "Keep body in a straight line, lower chest to floor, push back up."},
    {"name": "Chest Fly", "category": "Weight Training", "muscle_group": "Chest", "equipment": "Dumbbells",
     "difficulty": "Beginner", "instructions": "Lie on a bench, arms slightly bent, lower dumbbells out to sides then bring together above chest."},
    # Weight Training - Back
    {"name": "Deadlift", "category": "Weight Training", "muscle_group": "Back", "equipment": "Barbell",
     "difficulty": "Advanced", "instructions": "Keep back flat, hinge at hips, grip bar and lift by driving through heels."},
    {"name": "Pull-Up", "category": "Weight Training", "muscle_group": "Back", "equipment": "Pull-up Bar",
     "difficulty": "Intermediate", "instructions": "Hang from bar, pull chin above the bar, lower with control."},
    {"name": "Bent-Over Row", "category": "Weight Training", "muscle_group": "Back", "equipment": "Barbell",
     "difficulty": "Intermediate", "instructions": "Hinge forward, pull bar towards lower ribs, squeeze shoulder blades."},
    {"name": "Lat Pulldown", "category": "Weight Training", "muscle_group": "Back", "equipment": "Cable Machine",
     "difficulty": "Beginner", "instructions": "Pull bar down to upper chest, control the return, keep chest up."},
    # Weight Training - Legs
    {"name": "Squat", "category": "Weight Training", "muscle_group": "Legs", "equipment": "Barbell",
     "difficulty": "Intermediate", "instructions": "Feet shoulder-width apart, lower hips back and down, keep chest up, drive back up."},
    {"name": "Leg Press", "category": "Weight Training", "muscle_group": "Legs", "equipment": "Machine",
     "difficulty": "Beginner", "instructions": "Push platform away by extending knees and hips, control the return."},
    {"name": "Lunges", "category": "Weight Training", "muscle_group": "Legs", "equipment": "Dumbbells",
     "difficulty": "Beginner", "instructions": "Step forward, lower back knee toward floor, push back to start."},
    {"name": "Romanian Deadlift", "category": "Weight Training", "muscle_group": "Legs", "equipment": "Barbell",
     "difficulty": "Intermediate", "instructions": "Hinge at hips with slight knee bend, lower bar along legs, feel hamstring stretch."},
    # Weight Training - Shoulders
    {"name": "Overhead Press", "category": "Weight Training", "muscle_group": "Shoulders", "equipment": "Barbell",
     "difficulty": "Intermediate", "instructions": "Press bar overhead from shoulder height until arms are locked out."},
    {"name": "Lateral Raise", "category": "Weight Training", "muscle_group": "Shoulders", "equipment": "Dumbbells",
     "difficulty": "Beginner", "instructions": "Raise dumbbells out to sides until arms are parallel to floor."},
    # Weight Training - Arms
    {"name": "Bicep Curl", "category": "Weight Training", "muscle_group": "Arms", "equipment": "Dumbbells",
     "difficulty": "Beginner", "instructions": "Curl dumbbells up toward shoulders, keep elbows tucked, lower slowly."},
    {"name": "Tricep Dip", "category": "Weight Training", "muscle_group": "Arms", "equipment": "Bodyweight",
     "difficulty": "Intermediate", "instructions": "Lower body by bending elbows, push back up until arms are straight."},
    # Strength Training - Core
    {"name": "Plank", "category": "Strength Training", "muscle_group": "Core", "equipment": "Bodyweight",
     "difficulty": "Beginner", "instructions": "Hold a straight line from head to heels, engage core, avoid sagging hips."},
    {"name": "Hanging Leg Raise", "category": "Strength Training", "muscle_group": "Core", "equipment": "Pull-up Bar",
     "difficulty": "Advanced", "instructions": "Hang from bar, raise legs to hip height or higher, lower with control."},
    {"name": "Russian Twist", "category": "Strength Training", "muscle_group": "Core", "equipment": "Medicine Ball",
     "difficulty": "Beginner", "instructions": "Sit with knees bent, lean back slightly, rotate torso side to side."},
    # Cardio
    {"name": "Running", "category": "Cardio", "muscle_group": "Full Body", "equipment": "None",
     "difficulty": "Beginner", "instructions": "Maintain a steady pace, land midfoot, keep posture upright."},
    {"name": "Cycling", "category": "Cardio", "muscle_group": "Legs", "equipment": "Bike",
     "difficulty": "Beginner", "instructions": "Maintain steady cadence, adjust resistance for intensity."},
    {"name": "Jump Rope", "category": "Cardio", "muscle_group": "Full Body", "equipment": "Jump Rope",
     "difficulty": "Beginner", "instructions": "Small hops on balls of feet, rotate rope with wrists, keep steady rhythm."},
    {"name": "Rowing Machine", "category": "Cardio", "muscle_group": "Full Body", "equipment": "Rowing Machine",
     "difficulty": "Intermediate", "instructions": "Drive with legs, lean back slightly, pull handle to ribs, reverse smoothly."},
    {"name": "Burpees", "category": "Cardio", "muscle_group": "Full Body", "equipment": "Bodyweight",
     "difficulty": "Intermediate", "instructions": "Drop to a squat, kick feet back to plank, push up, jump feet forward, jump up."},
    {"name": "Stair Climber", "category": "Cardio", "muscle_group": "Legs", "equipment": "Machine",
     "difficulty": "Beginner", "instructions": "Maintain upright posture, take full steps, avoid leaning on handrails."},
]
